set -g prefix C-a

unbind-key C-b
bind-key C-a send-prefix

# Scrollback/History limit
set -g history-limit 2048

# Mouse
set-option -g -q mouse on

# Keybind preference
setw -g mode-keys vi
set-option -g status-keys vi

set -g @plugin 'tmux-plugins/tmux-yank'

# True color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*256col*:RGB"
